# -*- coding: utf-8 -*-
"""A9_Amazon reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oJb2OuwUeYwGSG84ixCgOzQsWpEo4Jwk
"""

from bs4 import BeautifulSoup as bs
import requests

link='https://www.amazon.in/Apple-iPhone-128GB-Space-Black/product-reviews/B0BDJ7P6NG/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews'

page = requests.get(link)

page

soup = bs(page.content,'html.parser')

print(soup.prettify())

names = soup.find_all('span',class_='a-profile-name')

names

cust_name = []
for i in range(0,9):
  cust_name.append(names[i].get_text())
cust_name

title = soup.find_all('a',class_='review-title-content')
title

review_title = []
for i in range(0,9):
  review_title.append(title[i].get_text())
review_title

rate = soup.find_all('span',class_='a-icon-alt')
rate

ratings = []
for i in range(0,9):
  ratings.append(rate[i].get_text())
ratings

review_content = soup.find_all('span',class_='a-size-base review-text review-text-content')
review_content

reviews = []
for i in range(0,9):
  reviews.append(review_content[i].get_text())
reviews[0]

import pandas as pd

print(len(cust_name))
print(len(review_title))
print(len(ratings))
print(len(reviews))

df = pd.DataFrame()
df['Customer Name']=cust_name
df['Review title']=review_title
df['Ratings']=ratings
df['Reviews']=reviews

df

from google.colab import files
df.to_csv('output.csv', encoding = 'utf-8-sig') 
files.download('output.csv')

